INSERT INTO [kck_projektDb].[dbo].[Notes] ([AuthorId], [Title], [Content], [Category], [ModifiedDate]) 
VALUES
(1, 'Plan zajęć na weekend', 'Sprawdzić harmonogram zajęć na siłowni. Zarezerwować miejsce na zajęcia z jogi w niedzielę.', 'Hobby', '2024-11-03'),
(1, 'Zakupy na święta', 'Kupić ozdoby świąteczne i prezenty dla rodziny. Przygotować listę zakupów spożywczych.', 'Home', '2024-11-15'),
(1, 'Zadanie projektowe', 'Pracować nad analizą danych dla projektu zespołowego. Przygotować prezentację na poniedziałkowe spotkanie.', 'Work', '2024-11-20'),
(1, 'Nauka do egzaminu', 'Powtórzyć materiał z fizyki, rozwiązać próbne zadania. Priorytet: działania na wektorach.', 'Studies', '2024-11-28'),
(1, 'Pomysł na nowy obraz', 'Spróbować namalować pejzaż inspirowany letnim porankiem. Kolory: pastelowe błękity i żółcie.', 'Hobby', '2022-06-15'),
(1, 'Lista rzeczy do spakowania', 'Paszport, bilety lotnicze, powerbank, ubrania na 7 dni, kosmetyki podróżne.', 'Other', '2023-09-05'),
(1, 'Spotkanie z klientem', 'Przygotować raport miesięczny i przećwiczyć prezentację wyników sprzedaży.', 'Work', '2023-02-18'),
(1, 'Renowacja kuchni', 'Zamówić nowe fronty do szafek, skonsultować wybór blatów z projektantem.', 'Home', '2023-03-12'),
(1, 'Zadanie domowe z literatury', 'Napisać analizę wiersza Norwida. Uwaga: skupić się na symbolice światła.', 'Studies', '2021-11-25'),
(1, 'Lista marzeń na rok 2025', 'Nauczyć się grać na pianinie, przebiec półmaraton, odwiedzić Norwegię.', 'Other', '2024-12-31'),
(1, 'Przepisy do wypróbowania', 'Spróbować zrobić domowe sushi i wegańskie curry.', 'Hobby', '2024-10-12'),
(1, 'Wizyta u lekarza', 'Umówić się na kontrolę u dentysty i badania okresowe.', 'Health', '2024-09-25'),
(1, 'Nowe książki do przeczytania', '"Lalka" Prusa, "Mistrz i Małgorzata" Bułhakowa, "Sapiens" Harariego.', 'Studies', '2024-08-14'),
(1, 'Cele zawodowe', 'Ukończyć kurs programowania w Pythonie, zdobyć certyfikat Scrum Master.', 'Work', '2024-07-20'),
(1, 'Wyjazd na wakacje', 'Zarezerwować hotel w Barcelonie, sprawdzić atrakcje turystyczne.', 'Other', '2024-06-30'),
(1, 'Plan treningowy', 'Ćwiczyć siłowo 3 razy w tygodniu, biegać w weekendy.', 'Health', '2024-05-10'),
(1, 'Nowe hobby', 'Zacząć uczyć się kaligrafii i fotografii analogowej.', 'Hobby', '2024-04-02'),
(1, 'Remont łazienki', 'Kupno nowych płytek, znalezienie fachowca.', 'Home', '2024-03-18'),
(1, 'Rodzinne spotkanie', 'Zorganizować urodziny babci, zamówić tort.', 'Other', '2024-02-14'),
(1, 'Nauka języka', 'Zacząć codziennie uczyć się hiszpańskiego przez 15 minut.', 'Studies', '2024-01-10'),
(1, 'Plany na weekend', 'Wyjście do teatru, spacer w parku, kolacja w ulubionej restauracji.', 'Other', '2024-02-02'),
(1, 'Nowe technologie', 'Poczytać o sztucznej inteligencji i jej zastosowaniach w biznesie.', 'Work', '2024-05-21'),
(1, 'Budżet domowy', 'Zaktualizować plan finansowy, sprawdzić miesięczne wydatki.', 'Home', '2024-06-15'),
(1, 'Dieta', 'Przygotować tygodniowy plan zdrowych posiłków.', 'Health', '2024-07-08'),
(1, 'Ogród', 'Zasadzić nowe kwiaty na balkonie, sprawdzić nawozy.', 'Hobby', '2024-08-28'),
(1, 'Fotografia', 'Zrobić zdjęcia zachodu słońca w plenerze.', 'Hobby', '2024-09-17');

INSERT INTO [kck_projektDb].[dbo].[Notes] ([AuthorId], [Title], [Content], [Category], [ModifiedDate]) 
VALUES
(1, 'Nowy plan diety', 'Opracować plan diety na podstawie zaleceń dietetyka. Ułożyć jadłospis na najbliższy tydzień.', 'Health', '2024-12-01'),
(1, 'Nowy projekt', 'Rozpocząć prace nad nowym projektem aplikacji mobilnej. Zbadać wymagania użytkowników.', 'Work', '2024-12-03'),
(1, 'Spotkanie rodzinne', 'Zorganizować spotkanie z rodziną na święta. Przygotować menu i zaproszenia.', 'Home', '2024-12-10'),
(1, 'Kurs online', 'Zarejestrować się na kurs programowania w Pythonie. Ukończyć moduł wprowadzający.', 'Studies', '2024-12-15'),
(1, 'Plan treningowy', 'Rozpisać nowy plan treningowy na siłowni. Uwzględnić ćwiczenia na wzmocnienie core.', 'Hobby', '2024-12-20'),
(1, 'Spotkanie zespołu', 'Zorganizować spotkanie zespołu w celu omówienia postępów projektu.', 'Work', '2024-12-23'),
(1, 'Święta Bożego Narodzenia', 'Przygotować dekoracje świąteczne i zorganizować świąteczne przyjęcie.', 'Home', '2024-12-24'),
(1, 'Sesja zdjęciowa', 'Zorganizować sesję zdjęciową na potrzeby portfolio. Wybór lokalizacji: park miejski.', 'Hobby', '2024-12-27'),
(1, 'Prezentacja wyników', 'Przygotować prezentację wyników kwartalnych. Skupić się na analizie sprzedaży.', 'Work', '2024-12-29'),
(1, 'Przegląd książki', 'Przeczytać książkę "Sztuka wojny" i napisać recenzję. Skupić się na strategiach zarządzania.', 'Other', '2024-12-31');


INSERT INTO [kck_projektDb].[dbo].[Notes] ([AuthorId], [Title], [Content], [Category], [ModifiedDate]) 
VALUES
(1, 'Przepis na ciasto marchewkowe', 'Skadniki: marchew, mka, jajka, cukier, orzechy. Pamitaj o dodaniu cynamonu!', 'Home', '2024-11-04'),
(1, 'Ksiki do przeczytania', 'Lista: "Wiedmin", "Sto lat samotnoci", "Mistrz i Magorzata". Sprawdzi dostpno w bibliotece.', 'Hobby', '2024-11-10'),
(1, 'Urodziny babci', 'Kup kwiaty i kartk z yczeniami. Zarezerwowa stolik w restauracji na niedzielny obiad.', 'Other', '2024-11-12'),
(1, 'Nowy projekt graficzny', 'Inspiracje: minimalizm, natura, kolory ziemi. Stworzy wstpne szkice logo.', 'Work', '2024-11-18'),
(1, 'Powtrka z chemii', 'Pierwiastki i zwizki chemiczne, reakcje redoks. Rozwiza zadania z podrcznika.', 'Studies', '2024-11-25'),
(1, 'Pomys na krtkie opowiadanie', 'Motyw: podr w czasie, zagubiony zegar. Bohater: samotny podrnik.', 'Hobby', '2022-07-01'),
(1, 'Lista zakupw na wycieczk', 'Plecak, buty trekkingowe, mapa, kompas, apteczka, prowiant.', 'Other', '2023-09-10'),
(1, 'Przygotowanie do konferencji', 'Stworzy prezentacj multimedialn, przygotowa odpowiedzi na pytania.', 'Work', '2023-02-20'),
(1, 'Naprawa roweru', 'Sprawdzi hamulce, wyregulowa przerzutki, napompowa opony.', 'Home', '2023-03-15'),
(1, 'Zadanie domowe z historii', 'Epoka renesansu we Woszech. Skupi si na sztuce i architekturze.', 'Studies', '2021-12-01'),
(1, 'Cele na nowy miesic', 'Codziennie czyta 30 minut, uprawia sport 3 razy w tygodniu, uczy si nowego sowa po angielsku.', 'Other', '2024-12-01'),
(1, 'Przepis na domowe pesto', 'Bazylia, orzeszki piniowe, parmezan, czosnek, oliwa z oliwek. Zmiksowa skadniki na gadk past.', 'Home', '2024-11-05'),
(1, 'Filmy do obejrzenia', '"Incepcja", "Nietykalni", "Forrest Gump". Sprawdzi recenzje i oceny.', 'Hobby', '2024-11-11'),
(1, 'Wizyta u dentysty', 'Przegld i czyszczenie zbw. Pamita o zabraniu karty pacjenta.', 'Other', '2024-11-13'),
(1, 'Projekt strony internetowej', 'Layout: prosty i intuicyjny. Kolory: stonowane i eleganckie. Dodanie formularza kontaktowego.', 'Work', '2024-11-19'),
(1, 'Powtrka z biologii', 'Ukad krenia, ukad nerwowy, procesy metaboliczne. Rozwiza testy z poprzednich lat.', 'Studies', '2024-11-26'),
(1, 'Pomys na wiersz', 'Temat: jesienny deszcz, melancholia. Metafory: szare chmury, opadajce licie.', 'Hobby', '2022-07-05'),
(1, 'Lista rzeczy do zabrania na piknik', 'Koc, koszyk piknikowy, napoje, owoce, kanapki, gry planszowe.', 'Other', '2023-09-12'),
(1, 'Przygotowanie do rozmowy kwalifikacyjnej', 'Przeanalizowa profil firmy, przygotowa odpowiedzi na typowe pytania.', 'Work', '2023-02-22'),
(1, 'Naprawa kosiarki', 'Sprawdzi wiec zaponow, wymieni filtr powietrza, naostrzy noe.', 'Home', '2023-03-18'),
(1, 'Zadanie domowe z geografii', 'Klimat i rolinno w strefie okoobiegunowej. Opisa wpyw zmian klimatycznych.', 'Studies', '2021-12-05');


INSERT INTO [kck_projektDb].[dbo].[Notes] ([AuthorId], [Title], [Content], [Category], [ModifiedDate]) 
VALUES
(1, 'Plan zajęć na weekend', 'Sprawdzić harmonogram zajęć na siłowni. Zarezerwować miejsce na zajęcia z jogi w niedzielę.', 'Hobby', '2024-11-03'),
(1, 'Zakupy na święta', 'Kupić ozdoby świąteczne i prezenty dla rodziny. Przygotować listę zakupów spożywczych.', 'Home', '2024-11-15'),
(1, 'Zadanie projektowe', 'Pracować nad analizą danych dla projektu zespołowego. Przygotować prezentację na poniedziałkowe spotkanie.', 'Work', '2024-11-20'),
(1, 'Nauka do egzaminu', 'Powtórzyć materiał z fizyki, rozwiązać próbne zadania. Priorytet: działania na wektorach.', 'Studies', '2024-11-28'),
(1, 'Pomysł na nowy obraz', 'Spróbować namalować pejzaż inspirowany letnim porankiem. Kolory: pastelowe błękity i żółcie.', 'Hobby', '2022-06-15'),
(1, 'Lista rzeczy do spakowania', 'Paszport, bilety lotnicze, powerbank, ubrania na 7 dni, kosmetyki podróżne.', 'Other', '2023-09-05'),
(1, 'Spotkanie z klientem', 'Przygotować raport miesięczny i przećwiczyć prezentację wyników sprzedaży.', 'Work', '2023-02-18'),
(1, 'Renowacja kuchni', 'Zamówić nowe fronty do szafek, skonsultować wybór blatów z projektantem.', 'Home', '2023-03-12'),
(1, 'Zadanie domowe z literatury', 'Napisać analizę wiersza Norwida. Uwaga: skupić się na symbolice światła.', 'Studies', '2021-11-25'),
(1, 'Lista marzeń na rok 2025', 'Nauczyć się grać na pianinie, przebiec półmaraton, odwiedzić Norwegię.', 'Other', '2024-12-31'),
(2, 'Trening biegowy', 'Przygotować plan na 10 km biegu. Wziąć udział w sobotnim parkrunie.', 'Hobby', '2024-10-10'),
(2, 'Remont łazienki', 'Zamówić nowe płytki i armaturę. Sprawdzić koszt wynajęcia ekipy remontowej.', 'Home', '2024-09-22'),
(2, 'Spotkanie z zespołem', 'Omówić postępy w projekcie aplikacji mobilnej. Przygotować notatki o błędach do poprawy.', 'Work', '2024-11-01'),
(2, 'Kurs programowania', 'Skończyć moduł o algorytmach sortowania. Zrobić zadania praktyczne z Pythona.', 'Studies', '2024-10-15'),
(1, 'Pomysł na bloga', 'Napisać wpis o podróżach budżetowych. Dodać zdjęcia z ostatniego wyjazdu.', 'Hobby', '2023-07-19'),
(3, 'Planowanie urodzin', 'Zarezerwować stolik w restauracji, zaprosić znajomych, wybrać tort.', 'Other', '2024-12-05'),
(3, 'Prezentacja marketingowa', 'Zebrać dane o kampanii reklamowej i stworzyć slajdy na spotkanie z zarządem.', 'Work', '2024-11-10'),
(1, 'Porządki w garażu', 'Posegregować narzędzia, oddać niepotrzebne rzeczy na aukcję charytatywną.', 'Home', '2024-08-30'),
(2, 'Nauka hiszpańskiego', 'Powtórzyć czasowniki nieregularne, obejrzeć odcinek serialu po hiszpańsku.', 'Studies', '2024-12-15'),
(1, 'Wycieczka rowerowa', 'Sprawdzić trasę nad jeziorem, przygotować prowiant i sprzęt.', 'Hobby', '2023-05-22'),
(3, 'Plan diety', 'Ułożyć jadłospis na tydzień, uwzględnić więcej warzyw i mniej cukru.', 'Other', '2024-11-25'),
(2, 'Konsultacja z księgową', 'Przygotować dokumenty finansowe za ostatni kwartał, omówić podatki.', 'Work', '2024-10-28'),
(1, 'Sesja zdjęciowa', 'Znaleźć plener na zdjęcia portretowe, sprawdzić pogodę na weekend.', 'Hobby', '2022-09-10'),
(1, 'Naprawa samochodu', 'Umówić się do mechanika na wymianę oleju i przeglądy hamulców.', 'Home', '2024-07-15'),
(2, 'Egzamin z matematyki', 'Przerobić zadania z równań różniczkowych, powtórzyć wzory.', 'Studies', '2024-12-20'),
(3, 'Pomysł na podcast', 'Nagrać odcinek o zarządzaniu czasem, przygotować pytania dla gościa.', 'Hobby', '2024-11-30'),
(1, 'Dekoracje na Halloween', 'Zrobić dyniowe lampiony, kupić cukierki dla dzieci.', 'Home', '2023-10-25'),
(2, 'Negocjacje z dostawcą', 'Przygotować ofertę cenową, ustalić harmonogram dostaw na grudzień.', 'Work', '2024-11-18'),
(3, 'Kurs rysunku', 'Ćwiczyć szkice postaci, przygotować portfolio na zajęcia.', 'Studies', '2024-10-05'),
(1, 'Lista książek do przeczytania', 'Dodać "Dune" i "1984" do kolekcji, zacząć od klasyki SF.', 'Hobby', '2024-01-15'),
(2, 'Planowanie wakacji', 'Sprawdzić loty do Grecji, zarezerwować hotel na lipiec.', 'Other', '2025-03-01'),
(3, 'Budżet domowy', 'Przeanalizować wydatki z listopada, ustalić limit na grudzień.', 'Home', '2024-12-02'),
(1, 'Trening siłowy', 'Zwiększyć obciążenie na martwym ciągu, zapisać progres w dzienniku.', 'Hobby', '2024-11-05'),
(2, 'Raport sprzedażowy', 'Zaktualizować dane z systemu CRM, wysłać raport do szefa.', 'Work', '2024-12-10'),
(3, 'Nauka gotowania', 'Wypróbować przepis na lasagne, kupić składniki w piątek.', 'Hobby', '2024-11-08');

INSERT INTO [kck_projektDb].[dbo].[Notes] ([AuthorId], [Title], [Content], [Category], [ModifiedDate]) 
VALUES
(1, 'Planowanie wakacji', 'Sprawdzić oferty last minute na wycieczki do Grecji. Zarezerwować lot i hotel.', 'Hobby', '2024-05-10'),
(1, 'Przepis na ciasto', 'Przygotować ciasto czekoladowe z malinami. Składniki: mąka, kakao, jajka, cukier, maliny.', 'Home', '2024-06-22'),
(1, 'Spotkanie z zespołem', 'Omówić postępy w projekcie. Przygotować agendę spotkania i listę pytań do dyskusji.', 'Work', '2024-07-15'),
(1, 'Nauka języka hiszpańskiego', 'Przerobić rozdział 5 z podręcznika. Ćwiczyć wymowę i nowe słownictwo.', 'Studies', '2024-08-30'),
(1, 'Remont łazienki', 'Kupić płytki ceramiczne i armaturę. Skontaktować się z hydraulikiem w sprawie instalacji.', 'Home', '2024-09-12'),
(1, 'Kurs fotografii', 'Zapisać się na kurs fotografii krajobrazowej. Przygotować sprzęt: aparat, obiektywy, statyw.', 'Hobby', '2024-10-05'),
(1, 'Prezentacja dla zarządu', 'Przygotować prezentację na temat nowej strategii marketingowej. Wykorzystać dane z ostatnich badań.', 'Work', '2024-11-18'),
(1, 'Nauka programowania', 'Rozwiązać zadania z algorytmów i struktur danych. Skupić się na sortowaniu przez scalanie.', 'Studies', '2024-12-01'),
(1, 'Planowanie urodzin', 'Zorganizować przyjęcie urodzinowe. Zamówić tort, dekoracje i zaprosić gości.', 'Other', '2024-12-20'),
(1, 'Zakup nowego laptopa', 'Porównać modele laptopów. Wybrać najlepszy w przedziale cenowym 3000-4000 zł.', 'Other', '2024-12-25'),
(1, 'Kurs gotowania', 'Zapisać się na kurs kuchni włoskiej. Przygotować listę potrzebnych składników.', 'Hobby', '2025-01-10'),
(1, 'Spotkanie z przyjaciółmi', 'Zaplanować wyjście do restauracji. Zarezerwować stolik na piątek wieczorem.', 'Other', '2025-01-15'),
(1, 'Nauka do certyfikatu', 'Przygotować się do egzaminu certyfikacyjnego z zarządzania projektami. Przerobić testy próbne.', 'Studies', '2025-02-01'),
(1, 'Remont pokoju', 'Wymienić tapetę i oświetlenie. Kupić nowe meble do pokoju.', 'Home', '2025-02-10'),
(1, 'Kurs tańca', 'Zapisać się na kurs tańca towarzyskiego. Przygotować wygodne buty do tańca.', 'Hobby', '2025-03-05'),
(1, 'Spotkanie z inwestorami', 'Przygotować prezentację na temat nowego projektu. Zebrać dane finansowe i prognozy.', 'Work', '2025-03-20'),
(1, 'Nauka do kolokwium', 'Powtórzyć materiał z matematyki. Rozwiązać zadania z rachunku różniczkowego.', 'Studies', '2025-04-01'),
(1, 'Planowanie ogrodu', 'Zaprojektować nowy układ roślin w ogrodzie. Kupić nasiona i narzędzia ogrodnicze.', 'Home', '2025-04-15'),
(1, 'Kurs rysunku', 'Zapisać się na kurs rysunku artystycznego. Przygotować szkicownik i ołówki.', 'Hobby', '2025-05-01'),
(1, 'Spotkanie z dostawcami', 'Omówić warunki nowej umowy. Przygotować listę wymagań i oczekiwań.', 'Work', '2025-05-10'),
(1, 'Nauka do egzaminu zawodowego', 'Przerobić materiały z ostatnich szkoleń. Rozwiązać testy próbne.', 'Studies', '2025-06-01'),
(1, 'Planowanie wycieczki rowerowej', 'Zaplanować trasę wycieczki rowerowej. Sprawdzić stan techniczny roweru.', 'Hobby', '2025-06-15'),
(1, 'Spotkanie z zespołem HR', 'Omówić plany rekrutacyjne na nowy rok. Przygotować prezentację z danymi.', 'Work', '2025-07-01'),
(1, 'Nauka do egzaminu językowego', 'Powtórzyć słownictwo i gramatykę. Rozwiązać testy próbne z języka angielskiego.', 'Studies', '2025-07-15'),
(1, 'Remont garażu', 'Wymienić drzwi garażowe. Skontaktować się z firmą remontową w sprawie wyceny.', 'Home', '2025-08-01'),
(1, 'Kurs medytacji', 'Zapisać się na kurs medytacji mindfulness. Przygotować wygodne ubranie i matę.', 'Hobby', '2025-08-15'),
(1, 'Spotkanie z klientem zagranicznym', 'Przygotować prezentację na temat oferty firmy. Przetłumaczyć materiały na język angielski.', 'Work', '2025-09-01'),
(1, 'Nauka do egzaminu z historii', 'Powtórzyć materiał z okresu II wojny światowej. Rozwiązać testy próbne.', 'Studies', '2025-09-15'),
(1, 'Planowanie przyjęcia świątecznego', 'Zorganizować przyjęcie świąteczne. Zamówić catering i dekoracje.', 'Other', '2025-12-01'),
(1, 'Zakup nowego telefonu', 'Porównać modele smartfonów. Wybrać najlepszy w przedziale cenowym 2000-3000 zł.', 'Other', '2025-12-15'),
(1, 'Kurs fotografii portretowej', 'Zapisać się na kurs fotografii portretowej. Przygotować sprzęt: aparat, obiektywy, lampy błyskowe.', 'Hobby', '2026-01-01'),
(1, 'Spotkanie z zespołem marketingowym', 'Omówić nową kampanię reklamową. Przygotować prezentację z danymi i analizami.', 'Work', '2026-01-15'),
(1, 'Nauka do egzaminu z chemii', 'Powtórzyć materiał z chemii organicznej. Rozwiązać zadania z reakcji chemicznych.', 'Studies', '2026-02-01'),
(1, 'Planowanie wyjazdu na narty', 'Zarezerwować nocleg i skipass. Przygotować sprzęt narciarski.', 'Hobby', '2026-02-15'),
(1, 'Spotkanie z klientem biznesowym', 'Przygotować ofertę współpracy. Zebrać dane i analizy rynkowe.', 'Work', '2026-03-01'),
(1, 'Nauka do egzaminu z biologii', 'Powtórzyć materiał z genetyki. Rozwiązać testy próbne.', 'Studies', '2026-03-15'),
(1, 'Remont salonu', 'Wymienić podłogę i oświetlenie. Kupić nowe meble do salonu.', 'Home', '2026-04-01'),
(1, 'Kurs gotowania sushi', 'Zapisać się na kurs gotowania sushi. Przygotować listę potrzebnych składników.', 'Hobby', '2026-04-15'),
(1, 'Spotkanie z zespołem projektowym', 'Omówić postępy w projekcie. Przygotować prezentację z danymi i analizami.', 'Work', '2026-05-01'),
(1, 'Nauka do egzaminu z geografii', 'Powtórzyć materiał z geografii fizycznej. Rozwiązać testy próbne.', 'Studies', '2026-05-15'),
(1, 'Planowanie wycieczki górskiej', 'Zaplanować trasę wycieczki górskiej. Sprawdzić stan techniczny sprzętu turystycznego.', 'Hobby', '2026-06-01'),
(1, 'Spotkanie z klientem korporacyjnym', 'Przygotować prezentację na temat nowej oferty. Zebrać dane i analizy rynkowe.', 'Work', '2026-06-15'),
(1, 'Nauka do egzaminu z matematyki', 'Powtórzyć materiał z algebry. Rozwiązać zadania z równań kwadratowych.', 'Studies', '2026-07-01'),
(1, 'Remont kuchni', 'Wymienić sprzęt AGD. Skontaktować się z firmą remontową w sprawie wyceny.', 'Home', '2026-07-15'),
(1, 'Kurs malowania akwarelami', 'Zapisać się na kurs malowania akwarelami. Przygotować farby, pędzle i papier.', 'Hobby', '2026-08-01'),
(1, 'Spotkanie z zespołem sprzedaży', 'Omówić wyniki sprzedaży za ostatni kwartał. Przygotować prezentację z danymi.', 'Work', '2026-08-15'),
(1, 'Nauka do egzaminu z fizyki', 'Powtórzyć materiał z termodynamiki. Rozwiązać zadania z przemian gazowych.', 'Studies', '2026-09-01'),
(1, 'Planowanie wyjazdu na wakacje', 'Zarezerwować nocleg i bilety lotnicze. Przygotować listę rzeczy do spakowania.', 'Hobby', '2026-09-15'),
(1, 'Spotkanie z klientem indywidualnym', 'Przygotować ofertę indywidualną. Zebrać dane i analizy rynkowe.', 'Work', '2026-10-01'),
(1, 'Nauka do egzaminu z informatyki', 'Powtórzyć materiał z programowania obiektowego. Rozwiązać zadania z języka Python.', 'Studies', '2026-10-15'),
(1, 'Remont łazienki', 'Wymienić płytki ceramiczne i armaturę. Skontaktować się z hydraulikiem w sprawie instalacji.', 'Home', '2026-11-01'),
(1, 'Kurs rysunku architektonicznego', 'Zapisać się na kurs rysunku architektonicznego. Przygotować szkicownik i ołówki.', 'Hobby', '2026-11-15'),
(1, 'Spotkanie z zespołem IT', 'Omówić nowe projekty technologiczne. Przygotować prezentację z danymi i analizami.', 'Work', '2026-12-01'),
(1, 'Nauka do egzaminu z historii sztuki', 'Powtórzyć materiał z okresu renesansu. Rozwiązać testy próbne.', 'Studies', '2026-12-15'),
(1, 'Planowanie przyjęcia sylwestrowego', 'Zorganizować przyjęcie sylwestrowe. Zamówić catering i dekoracje.', 'Other', '2026-12-31');